### PR TITLE
Bugfix: Fall back Default image wasn't being loaded.

### PR DESCRIPTION
**Pull request by n8-dev**
Issues fixed:
- [x]  `DefaultPageSocialImage`
- [x]  Added `twitter:image` to template for when `DefaultPageSocialImage` is used

### CODE REVIEW

**Comment by mooror** [comment]
I have also come across this issue in our installs as well. 

Can someone look into merging this and making another release?

**Comment by n8-dev** [comment]
Hi @samthejarvis I see you have actioned other merges and commits in this repo; any chance you could look at this?

**Review by samthejarvis — COMMENTED** [review]
Thanks for this. Could the vendor-specific items be removed from the `.gitignore`?

**Comment by n8-dev** [comment]
Is it needed? @samthejarvis they're just standard details from using two very common IDEs
(VsCode and any of the JetBrains tools)

**Comment by samthejarvis** [comment]
Generally prefer these are ignored locally for this purpose but not too precious about it :+1:

**Pull request merged**
